// Generated by gencpp from file option3_package/CustomService.msg
// DO NOT EDIT!


#ifndef OPTION3_PACKAGE_MESSAGE_CUSTOMSERVICE_H
#define OPTION3_PACKAGE_MESSAGE_CUSTOMSERVICE_H

#include <ros/service_traits.h>


#include <option3_package/CustomServiceRequest.h>
#include <option3_package/CustomServiceResponse.h>


namespace option3_package
{

struct CustomService
{

typedef CustomServiceRequest Request;
typedef CustomServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CustomService
} // namespace option3_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::option3_package::CustomService > {
  static const char* value()
  {
    return "7dbf19863255d8238636cddbc89afb50";
  }

  static const char* value(const ::option3_package::CustomService&) { return value(); }
};

template<>
struct DataType< ::option3_package::CustomService > {
  static const char* value()
  {
    return "option3_package/CustomService";
  }

  static const char* value(const ::option3_package::CustomService&) { return value(); }
};


// service_traits::MD5Sum< ::option3_package::CustomServiceRequest> should match
// service_traits::MD5Sum< ::option3_package::CustomService >
template<>
struct MD5Sum< ::option3_package::CustomServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::option3_package::CustomService >::value();
  }
  static const char* value(const ::option3_package::CustomServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::option3_package::CustomServiceRequest> should match
// service_traits::DataType< ::option3_package::CustomService >
template<>
struct DataType< ::option3_package::CustomServiceRequest>
{
  static const char* value()
  {
    return DataType< ::option3_package::CustomService >::value();
  }
  static const char* value(const ::option3_package::CustomServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::option3_package::CustomServiceResponse> should match
// service_traits::MD5Sum< ::option3_package::CustomService >
template<>
struct MD5Sum< ::option3_package::CustomServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::option3_package::CustomService >::value();
  }
  static const char* value(const ::option3_package::CustomServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::option3_package::CustomServiceResponse> should match
// service_traits::DataType< ::option3_package::CustomService >
template<>
struct DataType< ::option3_package::CustomServiceResponse>
{
  static const char* value()
  {
    return DataType< ::option3_package::CustomService >::value();
  }
  static const char* value(const ::option3_package::CustomServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTION3_PACKAGE_MESSAGE_CUSTOMSERVICE_H
