// Generated by gencpp from file option3_package/CustomServiceResponse.msg
// DO NOT EDIT!


#ifndef OPTION3_PACKAGE_MESSAGE_CUSTOMSERVICERESPONSE_H
#define OPTION3_PACKAGE_MESSAGE_CUSTOMSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace option3_package
{
template <class ContainerAllocator>
struct CustomServiceResponse_
{
  typedef CustomServiceResponse_<ContainerAllocator> Type;

  CustomServiceResponse_()
    : result(0)  {
    }
  CustomServiceResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::option3_package::CustomServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::option3_package::CustomServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CustomServiceResponse_

typedef ::option3_package::CustomServiceResponse_<std::allocator<void> > CustomServiceResponse;

typedef boost::shared_ptr< ::option3_package::CustomServiceResponse > CustomServiceResponsePtr;
typedef boost::shared_ptr< ::option3_package::CustomServiceResponse const> CustomServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::option3_package::CustomServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::option3_package::CustomServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::option3_package::CustomServiceResponse_<ContainerAllocator1> & lhs, const ::option3_package::CustomServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::option3_package::CustomServiceResponse_<ContainerAllocator1> & lhs, const ::option3_package::CustomServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace option3_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::option3_package::CustomServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::option3_package::CustomServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::option3_package::CustomServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::option3_package::CustomServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::option3_package::CustomServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::option3_package::CustomServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::option3_package::CustomServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::option3_package::CustomServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::option3_package::CustomServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "option3_package/CustomServiceResponse";
  }

  static const char* value(const ::option3_package::CustomServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::option3_package::CustomServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
"\n"
"\n"
;
  }

  static const char* value(const ::option3_package::CustomServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::option3_package::CustomServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::option3_package::CustomServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::option3_package::CustomServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTION3_PACKAGE_MESSAGE_CUSTOMSERVICERESPONSE_H
