// Generated by gencpp from file option3_package/CustomServiceRequest.msg
// DO NOT EDIT!


#ifndef OPTION3_PACKAGE_MESSAGE_CUSTOMSERVICEREQUEST_H
#define OPTION3_PACKAGE_MESSAGE_CUSTOMSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace option3_package
{
template <class ContainerAllocator>
struct CustomServiceRequest_
{
  typedef CustomServiceRequest_<ContainerAllocator> Type;

  CustomServiceRequest_()
    : a(0)
    , type(0)  {
    }
  CustomServiceRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , type(0)  {
  (void)_alloc;
    }



   typedef int32_t _a_type;
  _a_type a;

   typedef int32_t _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::option3_package::CustomServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::option3_package::CustomServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CustomServiceRequest_

typedef ::option3_package::CustomServiceRequest_<std::allocator<void> > CustomServiceRequest;

typedef boost::shared_ptr< ::option3_package::CustomServiceRequest > CustomServiceRequestPtr;
typedef boost::shared_ptr< ::option3_package::CustomServiceRequest const> CustomServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::option3_package::CustomServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::option3_package::CustomServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::option3_package::CustomServiceRequest_<ContainerAllocator1> & lhs, const ::option3_package::CustomServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::option3_package::CustomServiceRequest_<ContainerAllocator1> & lhs, const ::option3_package::CustomServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace option3_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::option3_package::CustomServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::option3_package::CustomServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::option3_package::CustomServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::option3_package::CustomServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::option3_package::CustomServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::option3_package::CustomServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::option3_package::CustomServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f7c33678d9a56955865f12a70fc3396";
  }

  static const char* value(const ::option3_package::CustomServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f7c33678d9a5695ULL;
  static const uint64_t static_value2 = 0x5865f12a70fc3396ULL;
};

template<class ContainerAllocator>
struct DataType< ::option3_package::CustomServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "option3_package/CustomServiceRequest";
  }

  static const char* value(const ::option3_package::CustomServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::option3_package::CustomServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 a\n"
"int32 type\n"
;
  }

  static const char* value(const ::option3_package::CustomServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::option3_package::CustomServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::option3_package::CustomServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::option3_package::CustomServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a);
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTION3_PACKAGE_MESSAGE_CUSTOMSERVICEREQUEST_H
